version: "3.8"

services:
  multi-agent-simulation:
    build: .
    container_name: multi-agent-simulation
    volumes:
      - ./logs:/app/logs
      - ./gifs:/app/gifs
      - ./scores:/app/scores
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "6006:6006" # TensorBoard port
    command: python main.py
